# Generated by Django 5.0.2 on 2024-02-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kgs', models.FloatField()),
                ('usd', models.FloatField()),
                ('euro', models.FloatField()),
                ('auca_fund', models.IntegerField(default=1)),
                ('email_field', models.EmailField(max_length=254)),
                ('email_confirm', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('auca_connection', models.IntegerField()),
                ('country', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=128)),
                ('first_comment', models.TextField()),
                ('last_comment', models.TextField(max_length=256)),
            ],
        ),
    ]
