# Generated by Django 5.0.2 on 2024-02-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='auca_connection',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='first_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='last_comment',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
