# Generated by Django 5.0.2 on 2024-02-26 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0002_alter_formmodel_auca_connection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='kgs',
            new_name='som',
        ),
    ]
