# Generated by Django 5.0.2 on 2024-02-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0004_alter_formmodel_auca_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='auca_connection',
            field=models.IntegerField(default=1),
        ),
    ]
