# Generated by Django 5.0.2 on 2024-02-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0006_alter_formmodel_auca_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='auca_fund',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
